[package]
name = "pop-support"
version = "2.0.0"
edition = "2024"
repository = "https://github.com/pop-os/support-panel"
license = "MPL-2.0"

[workspace]

[dependencies]
anyhow = "1.0.100"
as-result = "0.2.1"
async-pidfd = { version = "0.1.5", default-features = false, features = ["async"] }
compio-driver = "0.10.0"
compio-fs = "0.10.0"
compio-io = "0.8.4"
compio-runtime = "0.10.1"
concat-in-place = "1.1.0"
const_format = "0.2.35"
dirs = "6.0.0"
fomat-macros = "0.3.2"
futures = "0.3.31"
tempfile = "3.23.0"

[dependencies.clap]
version = "3.2"
features = ["derive"]
